---
- name: "AHV command"
  hosts: hv
  gather_facts: yes
  tasks:
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    - name: check ethtoool
      shell: "ethtool -S eth0"
      register: result
